# Generated by Django 4.1.1 on 2022-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options_alter_property_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='property.amenity'),
        ),
    ]
