# Generated by Django 4.1.1 on 2022-09-24 15:52

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_amenity_options_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='amenities'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='property_images'),
        ),
    ]
